### ISSUE TITLE
I am trying to use this bundle but I have this problem

### ISSUE THREAD

**Issue by ivanoterouvigo** [sunra/angularjs-symfony2-bundle#6]
Hi Sunra!

I follow your readme related to this bundle, but I have this problem.

<img width="414" alt="error_levantando_web_001" src="https://cloud.githubusercontent.com/assets/11814769/11841950/d15463f4-a400-11e5-8db1-2dbf4d13f0ff.png">

Can you help me?
Best regards.

**Comment by sunra** [comment]
From the screenshots you can see that the error is not related to angularjs-symfony2-bundle
